export const actionTypes = {
    START_FETCH_REPORTS: "START_FETCH_REPORTS",
    FETCH_REPORTS_SUCCESS: "FETCH_REPORTS_SUCCESS",
    FETCH_REPORTS_FAIL: "FETCH_REPORTS_FAIL",
    FILTER_REPORTS_SUCCESS: "FILTER_REPORTS_SUCCESS",
    FILTER_REPORTS_FAIL: "FILTER_REPORTS_FAIL",
    RECEIVE_INPUT_CHANGE: "RECEIVE_INPUT_CHANGE",
};