export const actionTypes = {
    START_FETCH_REPORTS: "START_FETCH_REPORTS",
    FETCH_REPORTS_SUCCESS: "FETCH_REPORTS_SUCCESS",
    FETCH_REPORTS_FAIL: "FETCH_REPORTS_FAIL",
    RECEIVE_INPUT_CHANGE: "RECEIVE_INPUT_CHANGE",
    OPEN_DETAILS_MODAL: "OPEN_DETAILS_MODAL",
    CLOSE_DETAILS_MODAL: "CLOSE_DETAILS_MODAL",
    OPEN_DELETE_MODAL: "OPEN_DELETE_MODAL",
    CLOSE_DELETE_MODAL: "CLOSE_DELETE_MODAL",
    START_DELETE_REPORT: "START_DELETE_REPORT",
    DELETE_REPORT_SUCCESS: "DELETE_REPORT_SUCCESS",
    DELETE_REPORT_FAIL: "DELETE_REPORT_FAIL"
};