export const actionTypes = {
    START_FETCH_REPORTS: "START_FETCH_REPORTS",
    FETCH_REPORTS_SUCCESS: "FETCH_REPORTS_SUCCESS",
    FETCH_REPORTS_FAIL: "FETCH_REPORTS_FAIL",
    NO_FILTER_RESULTS: "NO_FILTER_RESULTS",
    RECEIVE_INPUT_CHANGE: "RECEIVE_INPUT_CHANGE"
};